[pytest]
testpaths = tests
addopts = --junitxml=junit.xml
junit_family=legacy
markers =
    nightly: mark for nightly integration tests
    regression: mark for regression tests
    sg13g2: mark for IHP SG13G2 integration tests (requires Docker + IHP_PDK_ROOT)
    maxerrors: Maximum number of circuit errors to tolerate for nightly integration tests
[pytest-watch]
dont-watch-files = ^\.#
